events {
    worker_connections 1024;
}

http {
    upstream keycloakServer {
        # Nginx is listening on 8443 externally but talking to Keycloak (likely) on 8080 internally.
        server keycloak_admin_console:8080;
    }

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name _; # Matches any IP/Domain
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name _; 

        ssl_certificate     /etc/nginx/ssl/localhost/localhost.crt;
        ssl_certificate_key /etc/nginx/ssl/localhost/localhost.key;

        location / {
            proxy_pass http://keycloakServer;
            
            # Use $http_host to preserve the port if it's in the original request
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # CRITICAL for Keycloak SSL
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Port 8443;

            proxy_buffer_size          128k;
            proxy_buffers              4 256k;
            proxy_busy_buffers_size    256k;
        }
    }
}
